# Generated by Django 4.2 on 2023-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_userperfil_peso_alvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='nivel_de_atividade',
            field=models.DecimalField(decimal_places=2, help_text='0.2= Sedentário \n 0.3= Levemente Ativo \n 0.4= Moderadamente Ativo \n 0.5= Muito Ativo \n', max_digits=5, null=True, verbose_name='Nível de Atividade'),
        ),
    ]
