# Generated by Django 4.2 on 2023-04-16 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metas', '0001_initial'),
        ('perfil', '0003_alter_userperfil_nivel_de_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metas.metamacro', verbose_name='Macros')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.userperfil', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
    ]
