# Generated by Django 4.2 on 2023-04-16 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, null=True, verbose_name='Descrição')),
                ('carboidratos', models.FloatField(null=True, verbose_name='Carboidratos')),
                ('proteinas', models.FloatField(null=True, verbose_name='Proteinas')),
                ('gorduras', models.FloatField(null=True, verbose_name='Gorduras')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta Macro',
                'verbose_name_plural': 'Metas Macro',
            },
        ),
    ]
